# -*- coding: utf-8 -*-
"""datapreprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PlzM0FJRRmBwmK_Eco9dKGgLNTTLk3BJ
"""

import csv
import pandas as pd

data = pd.read_csv('data/mc1-reports-data.csv',parse_dates=['time'])

d = {}

for frame, val in data.groupby('location'):
    d[f'{frame}'] = val
len(d.keys())

ans = []
for k in d.keys():
  d[k]['DateTime'] = d[k]['time']
  d[k] = d[k].drop(['time'],axis = 1)
  d[k] = d[k].sort_values('DateTime')
  for i in d[k].keys():
    d[k][i] = d[k][i].fillna(0)
  groupval = d[k].groupby("DateTime")
  mean_val = groupval.mean()
  d[k] = mean_val.reset_index()
  ans.append(d[k])

for i in range(len(ans)):
  ans[i].to_csv(f'data/location{i+1}.tsv',index=False, sep='\t')